### Create new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: 

     {
    "title": "One for jess",
    "author": "Hello jess",
    "url": "https://onetwothree.com/",
    "likes": 42
    }

### Get all blogs
GET http://localhost:3001/api/blogs/

### Delete one blog
DELETE http://localhost:3001/api/blogs/638ba004d031f889ebc9aa03
Authorization: 

### Update blogs
PUT http://localhost:3001/api/blogs/638b9dde20002f23dc2a125f
Content-Type: application/json

     {
    "likes": 100
    }

### Create new users
POST http://localhost:3001/api/users
Content-Type: application/json
     
     {
          "username": "root",
          "name": "rooty",
          "password": "111"
     }

     #     {
     #      "username": "jess",
     #      "name": "jessy",
     #      "password": "222"
     # }
     
### Get all users
GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/users/638e42002387e192692a72a3

### Login with user
POST http://localhost:3001/api/login
Content-Type: application/json

{
     "username": "jess",
     "password": "222"
}

# {
#      "username": "root",
#      "password": "secret"
# }