POST http://localhost:3001/api/persons
Content-Type: application/json

    {
        "name": "Bo",
        "number": "555"
    }
###    
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/6380ebcbec234159f7cebd1b
###
GET http://localhost:3001/info
###
DELETE http://localhost:3001/api/persons/delete/6380ebcbec234159f7cebd1b
###
PUT http://localhost:3001/api/persons/637f9ccd8d9154fdf27d5db3
Content-Type: application/json

    {
        "name": "Te",
        "number": "666"
    }
